### ISSUE TITLE
custom layers in postgis

### ISSUE THREAD

**Issue by rishabhjain30** [mapzen/tileserver#105]
I have custom layers stored in postgres with geometry. How can I use tileserver to serve mvt from these layers?
Also, Is addition of more layers dynamically supported?

**Comment by rmarianski** [comment]
> I have custom layers stored in postgres with geometry. How can I use tileserver to serve mvt from these layers?

We don't have docs for this, but you can get started by looking at [queries.yaml](https://github.com/tilezen/vector-datasource/blob/e2ca30b2ed3865da1294f4a063a89653682f493d/queries.yaml). If you pick one of the layers that's already there and look through how it's configured and set up, you should be able to do the same to add in your own layer. You'll need to add a [jinja2 template file](https://github.com/tilezen/vector-datasource/tree/e2ca30b2ed3865da1294f4a063a89653682f493d/queries) too that will become the sql that gets used.

> Also, Is addition of more layers dynamically supported?

If you mean by being able to add to an already running tileserver, then no. But if you go through the configuration steps and restart then yes.

If you're looking for something more out of the box, have a look at [tilestache](http://tilestache.org/).

**Comment by radumas** [comment]
Hi @rishabhjain30, we're doing this as well. Starting with [our city's streets centerline layer](https://www1.toronto.ca/wps/portal/contentonly?vgnextoid=9acb5f9cd70bb210VgnVCM1000003dd60f89RCRD). We'll update this thread with our discoveries in the process.

**Comment by nvkelso** [comment]
We also recommend checking out the new PostGIS functionality to export MVT vector tiles directly without (also) making the extra Postgres > Tileserver hop. (Still may make sense for you to use Tilezen stack, but just FYI):

- https://postgis.net/docs/manual-dev/ST_AsMVT.html

**Comment by radumas** [comment]
Woah. Very cool feature from PostGIS.

So we're trying to modify the configs to work with our streets layer based on the `ne-roads` layer. I'm a little puzzled about some of the contents of [`vector-datasource/queries.yaml`](https://github.com/tilezen/vector-datasource/blob/master/queries.yaml). Specifically the following section (commented out lines were me):
```yaml
layers:
  roads:
    template: roads.jinja2
    geometry_types: [LineString, MultiLineString]
    simplify_start: 8
    transform:
      - vectordatasource.transform.tags_create_dict
#      - vectordatasource.transform.tags_name_i18n
#      - vectordatasource.transform.add_id_to_properties
#      - vectordatasource.transform.detect_osm_relation
      - vectordatasource.transform.parse_layer_as_float
#      - vectordatasource.transform.road_classifier
#      - vectordatasource.transform.road_oneway
      - vectordatasource.transform.road_abbreviate_name
      - vectordatasource.transform.route_name
#      - vectordatasource.transform.normalize_aerialways
#      - vectordatasource.transform.normalize_cycleway
#      - vectordatasource.transform.add_is_bicycle_related
#      - vectordatasource.transform.merge_networks_from_tags
#      - vectordatasource.transform.extract_network_information
#      - vectordatasource.transform.choose_most_important_network
      - vectordatasource.transform.road_trim_properties
      - vectordatasource.transform.remove_feature_id
#      - vectordatasource.transform.tags_remove
      - vectordatasource.transform.truncate_min_zoom_to_2dp
    sort: vectordatasource.sort.roads
    area-inclusion-threshold: 1
```
First of all I couldn't find a `roads.jinja2` file in that repository. There's a `yaml/roads.yaml` file, there's the `ne-roads.jinja2` which I modified to fit the our streets layer's schema, but no file I could find with that name. 

Second, I found that the lines like:
```yaml
    transform:
      - vectordatasource.transform.tags_create_dict
      - etc...
```
Correspond to python functions under [`vectordatasource/transform.py`](https://github.com/tilezen/vector-datasource/blob/master/vectordatasource/transform.py) and a number seem to be osm property specific. Is there an obvious way to know which should be applied to my data?

Thanks!
