### ISSUE TITLE
Is there a default SRID?

### ISSUE THREAD

**Issue by songololo** [mapzen/tileserver#32]
I'm wondering if there is a default SRID assumed for the underlying queries (bounding boxes etc?) And somewhat related, whether there is documentation available for the queries and template files?

I am trying a basic setup including a `queries.yaml` file as such:

```
all:
  - blocks_data

layers:
  blocks_data:
    start_zoom: 0
    area-inclusion-threshold: 1
    template: poly.jinja2
    clip: False
    clip_factor: 1
    geometry_types: [Polygon]
    transform: []
      # see https://github.com/tilezen/vector-datasource/blob/master/vectordatasource/transform.py
    sort: []
      # see: https://github.com/tilezen/vector-datasource/blob/master/vectordatasource/sort.py
    simplify_before_intersect: False
    simplify_start: 0

post_process: []
```

And a corresponding `poly.jinja2` file as follows:

```
SELECT
    "id" AS __id__,
    "param1",
    "param2",
    {% filter geometry %}geom{% endfilter %} AS __geometry__
FROM
    blocks_data
WHERE
    {{ bounds['polygon']|bbox_filter('geom') }}
```

I've tried this on a table with geometry represented in SRID 4326, which didn't return anything, so also tried on a table with the geometry stored in 3857, but no luck yet.

Thanks.
