### ISSUE TITLE
Redis caching problem on last config file

### ISSUE THREAD

**Issue by jkjeon0329** [mapzen/tileserver#91]
![redis_problem](https://cloud.githubusercontent.com/assets/27664210/25994945/06d44538-374b-11e7-8a4a-ece82d813639.png)

Anyone can help me? 
Thanks

```
# to cache tiles locally, enable a cache. This can be useful when
# experiencing timeouts for low or mid zoom ranges.

cache:
   type: redis
   redis:
     url: redis://localhost:6379
#    file:
#      prefix: /home/map/mapzen/tilequeue/tiles #directory_prefix
```
